// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Todo {
    "id": string;
    "noteId": string;
    "content": string;
    "completed": boolean;
    "priority": string;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
}
