// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetShowCompleted(): $CancellablePromise<string> {
    return $Call.ByID(2927444955);
}

export function SetShowCompleted(showCompleted: string): $CancellablePromise<void> {
    return $Call.ByID(2147604303, showCompleted);
}
