// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

export function Create(content: string): $CancellablePromise<model$0.Todo | null> {
    return $Call.ByID(180949469, content);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1271921866, id);
}

export function GetShowCompleted(): $CancellablePromise<string> {
    return $Call.ByID(172643551);
}

export function List(): $CancellablePromise<model$0.Todo[] | null> {
    return $Call.ByID(3842981121);
}

export function SetShowCompleted(showCompleted: string): $CancellablePromise<void> {
    return $Call.ByID(2638379787, showCompleted);
}

export function Toggle(id: string, completed: boolean): $CancellablePromise<void> {
    return $Call.ByID(607591045, id, completed);
}

export function UpdateContent(id: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(781007425, id, content);
}

export function UpdatePriority(id: string, priority: string): $CancellablePromise<void> {
    return $Call.ByID(3834533180, id, priority);
}
