// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * TODO
 */
export function AttachWindow(app: application$0.App | null, window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2890288284, app, window);
}

export function IsAutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(997869263);
}

export function IsStateVisible(state: model$0.WindowState | null): $CancellablePromise<boolean> {
    return $Call.ByID(3036489892, state);
}

export function LoadWindowSettings(): $CancellablePromise<model$0.WindowState | null> {
    return $Call.ByID(1539070376);
}

export function RestoreState(): $CancellablePromise<void> {
    return $Call.ByID(530125926);
}

export function SaveNow(): $CancellablePromise<void> {
    return $Call.ByID(3891643052);
}

export function ScheduleSave(): $CancellablePromise<void> {
    return $Call.ByID(2911789805);
}

export function SetAutostartEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3234795833, enabled);
}

export function SetLocked(locked: boolean): $CancellablePromise<void> {
    return $Call.ByID(3074266321, locked);
}

export function SetPinned(pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(3217312257, pinned);
}

export function SetupSystemTray(): $CancellablePromise<void> {
    return $Call.ByID(3915203415);
}
