// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../../log/slog/models.js";

export interface App {
    /**
     * Manager pattern for organized API
     */
    "Window": WindowManager | null;
    "ContextMenu": ContextMenuManager | null;
    "KeyBinding": KeyBindingManager | null;
    "Browser": BrowserManager | null;
    "Env": EnvironmentManager | null;
    "Dialog": DialogManager | null;
    "Event": EventManager | null;
    "Menu": MenuManager | null;
    "Screen": ScreenManager | null;
    "Clipboard": ClipboardManager | null;
    "SystemTray": SystemTrayManager | null;
    "Autostart": AutostartManager | null;
    "GlobalShortcut": GlobalShortcutManager | null;
    "Updater": updater$0.Updater | null;
    "Logger": slog$0.Logger | null;
}

/**
 * AutostartManager provides cross-platform control over whether the
 * application launches when the user logs in.
 * 
 * Registration takes effect on the next login, not immediately.
 * 
 * Platform behaviour:
 * 
 *   - macOS 13+ (bundled .app):  SMAppService.mainAppService — works for
 *     sandboxed and Mac-App-Store apps, no TCC automation prompt.
 *   - macOS (older or unbundled): a LaunchAgent plist is written to
 *     ~/Library/LaunchAgents/.
 *   - Windows: a value is added under
 *     HKCU\Software\Microsoft\Windows\CurrentVersion\Run.
 *   - Linux: an .desktop file is written to $XDG_CONFIG_HOME/autostart/
 *     (defaulting to ~/.config/autostart/).
 *   - Android / iOS / server builds: ErrAutostartNotSupported.
 */
export interface AutostartManager {
}

/**
 * BrowserManager manages browser-related operations
 */
export interface BrowserManager {
}

/**
 * ClipboardManager manages clipboard operations
 */
export interface ClipboardManager {
}

/**
 * ContextMenuManager manages all context menu operations
 */
export interface ContextMenuManager {
}

/**
 * DialogManager manages dialog-related operations
 */
export interface DialogManager {
}

/**
 * EnvironmentManager manages environment-related operations
 */
export interface EnvironmentManager {
}

/**
 * EventManager manages event-related operations
 */
export interface EventManager {
}

/**
 * GlobalShortcutManager manages application-wide (global) keyboard shortcuts.
 * 
 * Unlike menu accelerators or [KeyBindingManager] - which only fire while a
 * Wails window has focus - a global shortcut fires regardless of which
 * application is currently focused, as long as the Wails application is
 * running.
 * 
 * Global shortcuts are owned by the application, not by an individual window.
 * Registering the same accelerator twice within the same application is
 * reported as an error and the original binding is preserved; see [Register].
 * 
 * Shortcuts may be registered before [App.Run] is called: the binding with the
 * operating system is then deferred until the application starts.
 */
export interface GlobalShortcutManager {
}

/**
 * KeyBindingManager manages all key binding operations
 */
export interface KeyBindingManager {
}

/**
 * MenuManager manages menu-related operations
 */
export interface MenuManager {
}

export interface ScreenManager {
}

/**
 * SystemTrayManager manages system tray-related operations
 */
export interface SystemTrayManager {
}

export interface WebviewWindow {
}

/**
 * WindowManager manages all window-related operations
 */
export interface WindowManager {
}
