// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Updater is the singleton exposed as app.Updater. It is constructed during
 * application initialisation but does nothing useful until Init is called.
 */
export interface Updater {
}
